/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithPropertyRouteImport } from './routes/with-property'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as EmployeeCareRouteImport } from './routes/employee-care'
import { Route as CareRouteImport } from './routes/care'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalStaffRouteImport } from './routes/portal.staff'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalInvestorRouteImport } from './routes/portal.investor'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as CareStaffRouteImport } from './routes/care.staff'
import { Route as CarePrivacyRouteImport } from './routes/care.privacy'
import { Route as CareLoginRouteImport } from './routes/care.login'
import { Route as CareEmployeeRouteImport } from './routes/care.employee'
import { Route as CareAdminRouteImport } from './routes/care.admin'

const WithPropertyRoute = WithPropertyRouteImport.update({
  id: '/with-property',
  path: '/with-property',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCareRoute = EmployeeCareRouteImport.update({
  id: '/employee-care',
  path: '/employee-care',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffRoute = PortalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvestorRoute = PortalInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const CareStaffRoute = CareStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => CareRoute,
} as any)
const CarePrivacyRoute = CarePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => CareRoute,
} as any)
const CareLoginRoute = CareLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CareRoute,
} as any)
const CareEmployeeRoute = CareEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => CareRoute,
} as any)
const CareAdminRoute = CareAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRouteWithChildren
  '/employee-care': typeof EmployeeCareRoute
  '/portal': typeof PortalRouteWithChildren
  '/with-property': typeof WithPropertyRoute
  '/care/admin': typeof CareAdminRoute
  '/care/employee': typeof CareEmployeeRoute
  '/care/login': typeof CareLoginRoute
  '/care/privacy': typeof CarePrivacyRoute
  '/care/staff': typeof CareStaffRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/staff': typeof PortalStaffRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRouteWithChildren
  '/employee-care': typeof EmployeeCareRoute
  '/with-property': typeof WithPropertyRoute
  '/care/admin': typeof CareAdminRoute
  '/care/employee': typeof CareEmployeeRoute
  '/care/login': typeof CareLoginRoute
  '/care/privacy': typeof CarePrivacyRoute
  '/care/staff': typeof CareStaffRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/staff': typeof PortalStaffRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRouteWithChildren
  '/employee-care': typeof EmployeeCareRoute
  '/portal': typeof PortalRouteWithChildren
  '/with-property': typeof WithPropertyRoute
  '/care/admin': typeof CareAdminRoute
  '/care/employee': typeof CareEmployeeRoute
  '/care/login': typeof CareLoginRoute
  '/care/privacy': typeof CarePrivacyRoute
  '/care/staff': typeof CareStaffRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/staff': typeof PortalStaffRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/employee-care'
    | '/portal'
    | '/with-property'
    | '/care/admin'
    | '/care/employee'
    | '/care/login'
    | '/care/privacy'
    | '/care/staff'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login'
    | '/portal/staff'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/employee-care'
    | '/with-property'
    | '/care/admin'
    | '/care/employee'
    | '/care/login'
    | '/care/privacy'
    | '/care/staff'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login'
    | '/portal/staff'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/employee-care'
    | '/portal'
    | '/with-property'
    | '/care/admin'
    | '/care/employee'
    | '/care/login'
    | '/care/privacy'
    | '/care/staff'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login'
    | '/portal/staff'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRouteWithChildren
  EmployeeCareRoute: typeof EmployeeCareRoute
  PortalRoute: typeof PortalRouteWithChildren
  WithPropertyRoute: typeof WithPropertyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/with-property': {
      id: '/with-property'
      path: '/with-property'
      fullPath: '/with-property'
      preLoaderRoute: typeof WithPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-care': {
      id: '/employee-care'
      path: '/employee-care'
      fullPath: '/employee-care'
      preLoaderRoute: typeof EmployeeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staff': {
      id: '/portal/staff'
      path: '/staff'
      fullPath: '/portal/staff'
      preLoaderRoute: typeof PortalStaffRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/investor': {
      id: '/portal/investor'
      path: '/investor'
      fullPath: '/portal/investor'
      preLoaderRoute: typeof PortalInvestorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/care/staff': {
      id: '/care/staff'
      path: '/staff'
      fullPath: '/care/staff'
      preLoaderRoute: typeof CareStaffRouteImport
      parentRoute: typeof CareRoute
    }
    '/care/privacy': {
      id: '/care/privacy'
      path: '/privacy'
      fullPath: '/care/privacy'
      preLoaderRoute: typeof CarePrivacyRouteImport
      parentRoute: typeof CareRoute
    }
    '/care/login': {
      id: '/care/login'
      path: '/login'
      fullPath: '/care/login'
      preLoaderRoute: typeof CareLoginRouteImport
      parentRoute: typeof CareRoute
    }
    '/care/employee': {
      id: '/care/employee'
      path: '/employee'
      fullPath: '/care/employee'
      preLoaderRoute: typeof CareEmployeeRouteImport
      parentRoute: typeof CareRoute
    }
    '/care/admin': {
      id: '/care/admin'
      path: '/admin'
      fullPath: '/care/admin'
      preLoaderRoute: typeof CareAdminRouteImport
      parentRoute: typeof CareRoute
    }
  }
}

interface CareRouteChildren {
  CareAdminRoute: typeof CareAdminRoute
  CareEmployeeRoute: typeof CareEmployeeRoute
  CareLoginRoute: typeof CareLoginRoute
  CarePrivacyRoute: typeof CarePrivacyRoute
  CareStaffRoute: typeof CareStaffRoute
}

const CareRouteChildren: CareRouteChildren = {
  CareAdminRoute: CareAdminRoute,
  CareEmployeeRoute: CareEmployeeRoute,
  CareLoginRoute: CareLoginRoute,
  CarePrivacyRoute: CarePrivacyRoute,
  CareStaffRoute: CareStaffRoute,
}

const CareRouteWithChildren = CareRoute._addFileChildren(CareRouteChildren)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalInvestorRoute: typeof PortalInvestorRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalStaffRoute: typeof PortalStaffRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalInvestorRoute: PortalInvestorRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalStaffRoute: PortalStaffRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRouteWithChildren,
  EmployeeCareRoute: EmployeeCareRoute,
  PortalRoute: PortalRouteWithChildren,
  WithPropertyRoute: WithPropertyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
