/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithPropertyRouteImport } from './routes/with-property'
import { Route as IndexRouteImport } from './routes/index'

const WithPropertyRoute = WithPropertyRouteImport.update({
  id: '/with-property',
  path: '/with-property',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/with-property': typeof WithPropertyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/with-property': typeof WithPropertyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/with-property': typeof WithPropertyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/with-property'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/with-property'
  id: '__root__' | '/' | '/with-property'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithPropertyRoute: typeof WithPropertyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/with-property': {
      id: '/with-property'
      path: '/with-property'
      fullPath: '/with-property'
      preLoaderRoute: typeof WithPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithPropertyRoute: WithPropertyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
